
name: auto-run-test-flakesync

on: [push, pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.4'
          distribution: 'adopt'

      - name: Installs packages
        run: mvn install -B
