name: auto-run-test-flakesync

on: [push, pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8.0.292+10'
          distribution: 'adopt'

      - name: Installs packages
        run: mvn install -B
